return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate",
	lazy = false,
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"diff",
			"html",
			"lua",
			"luadoc",
			"markdown",
			"markdown_inline",
			"query",
			"vim",
			"vimdoc",
			"rust",
			"regex",
			"php",
			"blade",
			"gitignore",
			"javascript",
			"typescript",
			"tsx",
			"css",
			"json",
			"jsonc",
			"yaml",
			"prisma",
			"latex",
		},
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
	},
}
